""" add_staff_role

Revision ID: 36357487ff9e
Revises: 865a1c4222ba
Create Date: 2026-06-16 00:34:42.588651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36357487ff9e'
down_revision: Union[str, Sequence[str], None] = '865a1c4222ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'staff_role')
    op.add_column('addresses', sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('province_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('ward_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_news_slug'), table_name='news')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
