"""Add is_public to Promotion

Revision ID: 3b397c2078ac
Revises: c8a5f2e91d3b
Create Date: 2026-07-22 13:27:23.645271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b397c2078ac'
down_revision: Union[str, Sequence[str], None] = 'c8a5f2e91d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotions', 'is_public')
    # ### end Alembic commands ###
