"""update_schema

Revision ID: 3bee34dbdf4a
Revises: abed78f2d91f
Create Date: 2026-06-26 13:00:46.111097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bee34dbdf4a'
down_revision: Union[str, Sequence[str], None] = 'abed78f2d91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('province_id', sa.Integer(), nullable=True))
    op.add_column('addresses', sa.Column('district_id', sa.Integer(), nullable=True))
    op.add_column('addresses', sa.Column('ward_code', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('admin_reply', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'is_hidden')
    op.drop_column('reviews', 'admin_reply')
    op.drop_column('addresses', 'ward_code')
    op.drop_column('addresses', 'district_id')
    op.drop_column('addresses', 'province_id')
    # ### end Alembic commands ###
