"""Add missing fields

Revision ID: 6bb296dac548
Revises: 865a1c4222ba
Create Date: 2026-06-16 22:30:25.522666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb296dac548'
down_revision: Union[str, Sequence[str], None] = '865a1c4222ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_index(op.f('ix_news_slug'), 'news', ['slug'], unique=True)
    op.drop_column('addresses', 'province_id')
    op.drop_column('addresses', 'ward_code')
    op.drop_column('addresses', 'district_id')
    op.add_column('orders', sa.Column('shipping_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('staff_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'staff_role')
    op.drop_column('orders', 'shipping_provider')
    op.add_column('addresses', sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('ward_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('province_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_news_slug'), table_name='news')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
