"""Detailed E-commerce Schema

Revision ID: aa0335b52c80
Revises: a7ca31beda2d
Create Date: 2026-06-09 19:47:09.772009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa0335b52c80'
down_revision: Union[str, Sequence[str], None] = 'a7ca31beda2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('link_url', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banners_id'), 'banners', ['id'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('promotions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('min_order_value', sa.Float(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_code'), 'promotions', ['code'], unique=True)
    op.create_index(op.f('ix_promotions_id'), 'promotions', ['id'], unique=False)
    op.create_table('compatibility_overrides',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id_1', sa.String(), nullable=False),
    sa.Column('product_id_2', sa.String(), nullable=False),
    sa.Column('is_compatible', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id_1'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_id_2'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compatibility_overrides_id'), 'compatibility_overrides', ['id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.create_table('product_skus',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('sku_code', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('promotional_price', sa.Float(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_skus_id'), 'product_skus', ['id'], unique=False)
    op.create_index(op.f('ix_product_skus_sku_code'), 'product_skus', ['sku_code'], unique=True)
    op.create_table('sku_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sku_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sku_images_id'), 'sku_images', ['id'], unique=False)
    op.create_table('review_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_images_id'), 'review_images', ['id'], unique=False)
    op.add_column('cart_items', sa.Column('sku_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('cart_items_product_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'product_skus', ['sku_id'], ['id'])
    op.drop_column('cart_items', 'product_id')
    op.add_column('categories', sa.Column('parent_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    op.add_column('order_items', sa.Column('sku_id', sa.String(), nullable=False))
    op.add_column('order_items', sa.Column('sku_code', sa.String(), nullable=False))
    op.add_column('order_items', sa.Column('price_at_purchase', sa.Float(), nullable=False))
    op.drop_constraint(op.f('order_items_product_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'product_skus', ['sku_id'], ['id'])
    op.drop_column('order_items', 'product_id')
    op.drop_column('order_items', 'product_price')
    op.add_column('orders', sa.Column('promotion_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('discount_amount', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'orders', 'promotions', ['promotion_id'], ['id'])
    op.add_column('products', sa.Column('brand_id', sa.String(), nullable=True))
    op.add_column('products', sa.Column('specifications', sa.JSON(), nullable=False))
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.drop_column('products', 'price')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'discount_price')
    op.drop_column('products', 'images')
    op.add_column('reviews', sa.Column('sku_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('reviews_product_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'product_skus', ['sku_id'], ['id'])
    op.drop_column('reviews', 'product_id')
    op.add_column('wishlist_items', sa.Column('sku_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('wishlist_items_product_id_fkey'), 'wishlist_items', type_='foreignkey')
    op.create_foreign_key(None, 'wishlist_items', 'product_skus', ['sku_id'], ['id'])
    op.drop_column('wishlist_items', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist_items', sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'wishlist_items', type_='foreignkey')
    op.create_foreign_key(op.f('wishlist_items_product_id_fkey'), 'wishlist_items', 'products', ['product_id'], ['id'])
    op.drop_column('wishlist_items', 'sku_id')
    op.add_column('reviews', sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_product_id_fkey'), 'reviews', 'products', ['product_id'], ['id'])
    op.drop_column('reviews', 'sku_id')
    op.add_column('products', sa.Column('images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('discount_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'specifications')
    op.drop_column('products', 'brand_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'promotion_id')
    op.add_column('order_items', sa.Column('product_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_product_id_fkey'), 'order_items', 'products', ['product_id'], ['id'])
    op.drop_column('order_items', 'price_at_purchase')
    op.drop_column('order_items', 'sku_code')
    op.drop_column('order_items', 'sku_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'parent_id')
    op.add_column('cart_items', sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_product_id_fkey'), 'cart_items', 'products', ['product_id'], ['id'])
    op.drop_column('cart_items', 'sku_id')
    op.drop_index(op.f('ix_review_images_id'), table_name='review_images')
    op.drop_table('review_images')
    op.drop_index(op.f('ix_sku_images_id'), table_name='sku_images')
    op.drop_table('sku_images')
    op.drop_index(op.f('ix_product_skus_sku_code'), table_name='product_skus')
    op.drop_index(op.f('ix_product_skus_id'), table_name='product_skus')
    op.drop_table('product_skus')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_compatibility_overrides_id'), table_name='compatibility_overrides')
    op.drop_table('compatibility_overrides')
    op.drop_index(op.f('ix_promotions_id'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_code'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_banners_id'), table_name='banners')
    op.drop_table('banners')
    # ### end Alembic commands ###
