"""add image_url to chat_messages

Revision ID: abed78f2d91f
Revises: 45786b5f8378
Create Date: 2026-06-22 14:18:20.663582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abed78f2d91f'
down_revision: Union[str, Sequence[str], None] = '45786b5f8378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('chat_messages', 'image_url')
    # ### end Alembic commands ###
