"""Add ReviewLike table

Revision ID: b9173786aa73
Revises: f0fa41fa695c
Create Date: 2026-07-13 12:48:39.131437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9173786aa73'
down_revision: Union[str, Sequence[str], None] = 'f0fa41fa695c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_likes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_likes_id'), 'review_likes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_likes_id'), table_name='review_likes')
    op.drop_table('review_likes')
    # ### end Alembic commands ###
