"""add flash sales

Revision ID: d7ee620add1a
Revises: b9173786aa73
Create Date: 2026-07-17 20:53:30.219490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7ee620add1a'
down_revision: Union[str, Sequence[str], None] = 'b9173786aa73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flash_sales',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flash_sales_id'), 'flash_sales', ['id'], unique=False)
    op.create_table('flash_sale_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('flash_sale_id', sa.String(), nullable=False),
    sa.Column('product_sku_id', sa.String(), nullable=False),
    sa.Column('flash_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flash_sale_id'], ['flash_sales.id'], ),
    sa.ForeignKeyConstraint(['product_sku_id'], ['product_skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flash_sale_items_id'), 'flash_sale_items', ['id'], unique=False)
    op.alter_column('reviews', 'admin_reply',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('reviews', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(None, 'suppliers', 'brands', ['brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.alter_column('reviews', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('reviews', 'admin_reply',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_flash_sale_items_id'), table_name='flash_sale_items')
    op.drop_table('flash_sale_items')
    op.drop_index(op.f('ix_flash_sales_id'), table_name='flash_sales')
    op.drop_table('flash_sales')
    # ### end Alembic commands ###
